spring:
  main:
    banner-mode: 'off'
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: false
      path: /h2c

camel:
  springboot:
    main-run-controller: true
